FROM php:7.4-fpm-alpine

COPY . /var/www/html

WORKDIR /var/www/html

RUN docker-php-ext-install pdo pdo_mysql 


# RUN chmod -R 777 /var/www/storage \
#         /var/www/bootstrap/cache

# RUN php artisan key:generate
# RUN php artisan config:clear
# RUN php artisan config:cache
# RUN php artisan optimize